export const toolbarPresets: { [key: string]: string[] } = {
  compact: [
    "Bold",
    "Italic",
    "Underline",
    "Heading 1",
    "Heading 2",
    "Heading 3",
    "Link",
    "Image",
    "Table",
    "Inline Code",
    "Code Block",
  ],
  default: [
    "Bold",
    "Italic",
    "Strikethrough",
    "Heading 1",
    "Heading 2",
    "Heading 3",
    "Bullet List",
    "Numbered List",
    "Task List",
    "Blockquote",
    "Horizontal Rule",
    "Link",
    "Image",
    "Table",
    "Inline Code",
    "Code Block",
    "Mermaid Diagram",
  ],
  full: [
    "Bold",
    "Italic",
    "Strikethrough",
    "Underline",
    "Heading 1",
    "Heading 2",
    "Heading 3",
    "Heading 4",
    "Heading 5",
    "Heading 6",
    "Bullet List",
    "Numbered List",
    "Task List",
    "Blockquote",
    "Horizontal Rule",
    "Link",
    "Image",
    "Table",
    "Inline Code",
    "Code Block",
    "Mermaid Diagram",
    "Superscript",
    "Subscript",
    "Center Align",
    "HTML Block",
  ],
};
